apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-site
  namespace: personal-site
  labels:
    public: "true"
    app: personal-site
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-site
  template:
    metadata:
      labels:
        app: personal-site
        public: "true"
    spec:
      imagePullSecrets:
        - name: ghcr-token
      containers:
        - name: nginx
          image: ghcr.io/pmkuny/about.kuny.me:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
