apiVersion: v1
kind: Service
metadata:
  name: personal-site
  namespace: personal-site
  labels:
    public: "true"
    app: personal-site
spec:
  selector:
    app: personal-site
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
