apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-cm
  namespace: monitoring

data:
  alloy.yaml: |
    logging {
      level  = "info"
      format = "logfmt"
    }


    //
    // Kubernetes discovery
    //

    discovery.kubernetes "pods" {
      role = "pod"
    }


    //
    // Pod metrics scraping
    //

    prometheus.scrape "pods" {

      targets = discovery.kubernetes.pods.targets

      scrape_interval = "30s"

      forward_to = [
        prometheus.remote_write.default.receiver,
      ]

      scrape_protocols = ["PrometheusText0.0.4"]
    }


    //
    // Pod logs
    //

    loki.source.kubernetes "pods" {

      targets = discovery.kubernetes.pods.targets

      forward_to = [
        loki.process.pods.receiver,
      ]
    }


    loki.process "pods" {

      stage.static_labels {
        values = {
          cluster = "kubernetes",
        }
      }


      stage.labels {
        values = {
          namespace = "namespace",
          pod       = "pod",
          container = "container",
        }
      }


      forward_to = [
        loki.write.default.receiver,
      ]
    }



    //
    // Kubernetes events
    //

    loki.source.kubernetes_events "events" {

      forward_to = [
        loki.write.default.receiver,
      ]
    }



    //
    // OTLP receiver
    //

    otelcol.receiver.otlp "default" {

      grpc {
        endpoint = "0.0.0.0:4317"
      }


      http {
        endpoint = "0.0.0.0:4318"
      }


      output {
        metrics = [
          otelcol.processor.batch.default.input,
        ]

        logs = [
          otelcol.processor.batch.default.input,
        ]

        traces = [
          otelcol.processor.batch.default.input,
        ]
      }
    }



    //
    // Batch telemetry
    //

    otelcol.processor.batch "default" {

      output {

        metrics = [
          otelcol.exporter.prometheus.default.input,
        ]


        logs = [
          otelcol.exporter.loki.default.input,
        ]


        traces = [
          otelcol.exporter.otlp.default.input,
        ]
      }
    }



    //
    // Metrics -> Prometheus
    //

    otelcol.exporter.prometheus "default" {

      forward_to = [
        prometheus.remote_write.default.receiver,
      ]
    }


    prometheus.remote_write "default" {

      endpoint {
        url = "http://${PROMETHEUS_CLUSTER_IP}/api/v1/write"
      }


      external_labels = {
        cluster = "kubernetes",
      }
    }



    //
    // Logs -> Loki
    //

    otelcol.exporter.loki "default" {

      forward_to = [
        loki.write.default.receiver,
      ]
    }


    loki.write "default" {

      endpoint {
        url = "http://${LOKI_CLUSTER_IP}/loki/api/v1/push"
      }
    }



    //
    // Traces -> Tempo
    //

    otelcol.exporter.otlp "default" {

      client {

        endpoint = "${TEMPO_CLUSTER_IP}:4317"

        tls {
          insecure = true
        }
      }
    }
