apiVersion: v1
kind: ConfigMap
metadata:
  name: alloy-cm
  namespace: monitoring
data:
  alloy.yaml: |
    logging {
      level  = "info"
      format = "logfmt"
    }

    otelcol.receiver.otlp "default" {
      grpc {
        endpoint = "0.0.0.0:4317"
      }

      http {
        endpoint = "0.0.0.0:4318"
      }

      output {
        metrics = [otelcol.processor.batch.default.input]
        logs    = [otelcol.processor.batch.default.input]
        traces  = [otelcol.processor.batch.default.input]
      }
    }

    // Batching everything before routing to output

    otelcol.processor.batch "default" {
      output {
        metrics = [otelcol.exporter.prometheus.default.input]
        logs    = [otelcol.exporter.loki.default.input]
        traces  = [otelcol.exporter.otlp.default.input]
      }
    }

    // Metrics to Prom
    otelcol.exporter.prometheus "default" {
      forward_to = [prometheus.remote_write.default.receiver]
    }

    prometheus.remote_write "default" {

      endpoint {
        url = "http://${PROMETHEUS_CLUSTER_IP}/api/v1/write"
      }
    }


    // Logs to Loki
    otelcol.exporter.loki "default" {
      forward_to = [loki.write.default.receiver]
    }

    loki.write "default" {

      endpoint {
        url = "http://YOUR_LOKI/loki/api/v1/push"
      }
    }


    // Traces -> Tempo (maybe)
    otelcol.exporter.otlp "default" {

      client {
        endpoint = "YOUR_TEMPO:4317"

        tls {
          insecure = true
        }
      }
    }
