apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-loki-cm
  namespace: logs
data:
  values.yaml: |
    loki:
      storage:
        type: s3
        s3:
          endpoint: ${LOKI_S3_ENDPOINT}
          region: ${LOKI_S3_REGION}
    schema_config:
      configs:
        - from: 2024-01-01
          object_store: s3
          store: tsdb
          schema: v13
          index:
            prefix: index_
            period: 24h
