apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secret-bw-auth-token.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - configmap.yaml

labels:
  - pairs:
      managed-by: flux
