apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - about-kuny-me.yaml
  - adguard-home.yaml
  - cloudflared.yaml
  - external-dns.yaml
  - external-secrets.yaml
  - longhorn-system.yaml
  - metallb-system.yaml
  - monitoring.yaml
  - metrics.yaml
  - logs.yaml
  - scraparr.yaml
  - traces.yaml

labels:
  - pairs:
      managed-by: flux
