---
- name: Ensure SSHD enabeld
  ansible.builtin.systemd_service:
    name: sshd
    state: started
    enabled: true

- name: User present
  ansible.builtin.user:
    name: patch
    append: true


- name: Propogate Ansible SSH Key
  ansible.posix.authorized_key:
    user: patch
    key: "{{ lookup('url', 'https://github.com/pmkuny.keys') }}"
    state: present
    manage_dir: true
