---
- name: Ensure SSHD enabeld
  ansible.builtin.systemd_service:
    name: sshd
    state: started
    enabled: true

- name: User present
  ansible.builtin.user:
    name: patch
    groups: wheel,docker
    append: true


- name: Propogate Ansible SSH Key
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
    manage_dir: true