apiVersion: apps/v1
kind: Deployment
metadata:
  name: about-kuny-me
  namespace: about-kuny-me
  labels:
    public: "true"
    app: about-kuny-me
spec:
  replicas: 1
  selector:
    matchLabels:
      app: about-kuny-me
  template:
    metadata:
      labels:
        app: about-kuny-me
        public: "true"
    spec:
      imagePullSecrets:
        - name: ghcr-token
      containers:
        - name: nginx
          image: ghcr.io/pmkuny/about.kuny.me:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
