apiVersion: v1
kind: Service
metadata:
  name: about-kuny-me
  namespace: about-kuny-me
  labels:
    public: "true"
    app: about-kuny-me
spec:
  selector:
    app: about-kuny-me
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
