apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  namespace: adguard-home
  labels:
    lan_expose: "true"
    app: adguard-home
spec:
  selector:
    matchLabels:
      app: adguard-home
  replicas: 1
  template:
    metadata:
      labels:
        lan_expose: "true"
        app: adguard-home
    spec:
      volumes:
        - name: vol-appdata
          persistentVolumeClaim:
            claimName: adguard-home-pvc
      containers:
        - name: adguard-home
          image: docker.io/adguard/adguardhome
          ports:
            - containerPort: 53
              protocol: udp
            - containerPort: 53
              protocol: tcp
            - containerPort: 80
              protocol: tcp
            - containerPort: 443
              protocol: tcp
            - containerPort: 853
              protocol: tcp
          volumeMounts:
            - name: vol-appdata
              mountPath: /opt/adguardhome/conf
              subPath: config
            - name: vol-appdata
              mountPath: /opt/adguardhome/work
              subPath: work
