apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: adguard-home-pvc
  namespace: adguard-home
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-static
  resources:
    requests:
      storage: 500Mi
