apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: flux-system
data:
  PROMETHEUS_CLUSTER_IP: "10.96.197.119"
  LOKI_CLUSTER_IP: "0.0.0.0"
  TEMPO_CLUSTER_IP: "0.0.0.0"
  LOKI_S3_ENDPOINT: "s3.us-west-2.amazonaws.com"
  LOKI_S3_REGION: "us-west-2"
